<a href="https://colab.research.google.com/github/baghelrashmi04/Smart-EV-grid-optmization-Demand-Engine/blob/main/Global_ev_charing_station.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [ ]:
import pandas as pd
import numpy as np

dff=pd.read_csv("/content/drive/MyDrive/global_ev_charging_station.csv")

In [ ]:
dff

,StationID,UUID,DataProviderID,Operator,UsageType,UsageCost,AddressTitle,AddressLine1,Town,StateOrProvince,Postcode,Country,Latitude,Longitude,MaxPowerKW,FastChargeCount,ConnectionTypes,StatusType,YearCreated
0,473101,5B1E6265-45A9-4D0E-83A7-AB49D84D0BB2,1,Tesla (including non-tesla),Public,NaN,Tesla Supercharger,Purley Way,NaN,NaN,NaN,United Kingdom,51.371709,-0.116955,250.0,1,CCS (Type 2),Operational,2026
1,472908,A5EA67A8-756B-4C09-B578-BAEC40AEA237,1,Lidl,Public - Membership Required,£0.57/kWh,Positive Energy - DoubleTree by Hilton Manches...,Outwood Road,Wythenshawe,England,M90 4HL,United Kingdom,53.366453,-2.269799,11.0,0,Type 2 (Socket Only),Operational,2026
2,472220,1CCABB37-2CE5-49D4-8DC0-5025BE976BA1,1,EZO (IE),Public - Membership Required,NaN,Holiday Inn Express,106 University Street,Belfast,NaN,BT7 1HP,United Kingdom,54.586836,-5.926869,50.0,1,CCS (Type 2),Operational,2025
3,471954,0E7B7267-6DEE-4E85-91F4-D11B8FF789A9,1,BMM Energy (UK),Public - Membership Required,NaN,South Tyrone Hospital,Carland Road,Dungannon,NaN,BT71 4AU,United Kingdom,54.509453,-6.768057,22.0,0,Type 2 (Socket Only),Operational,2025
4,471953,A4E4A241-BF88-4394-99B2-B0B788FE3287,1,BMM Energy (UK),Public - Membership Required,NaN,Armagh Community Hospital,Victoria Grove,Armagh,NaN,BT61 9DH,United Kingdom,54.350644,-6.641787,22.0,0,Type 2 (Socket Only),Operational,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257580,267627,6152215D-9092-4602-B8BD-83190BB84042,1,(Unknown Operator),Public,0.4€ per kw,Hypercharger CCS2 & GB/T - EuroJeta Sh.P.K.,Pavarësia,NaN,NaN,23050,Kosovo,42.315385,20.806214,120.0,1,CCS (Type 2),Operational,2023
257581,267517,B3E5A178-946A-4E79-B08B-5B41AF495588,1,(Unknown Operator),Public - Pay At Location,0.15 €/kWh,Hotel Gracanica,Dragana Ristića,Gracanica,NaN,10500,Kosovo,42.600458,21.186628,22.0,0,Type 2 (Socket Only),Operational,2023
257582,147836,0DCB853D-A434-4B51-A295-DC73D5EC3BEC,1,(Business Owner at Location),Public,0.29€\kWh,Shell Prishtina,Rrafshi i Kosovës,Çagllavicë (Prishtinë),Municipality of Pristina,2071,Kosovo,42.631876,21.145781,50.0,2,"CCS (Type 2), CHAdeMO, Type 2 (Tethered Connec...",Operational,2020
257583,147835,2E5B98D1-6C0D-4E9E-AEE1-805211211358,1,(Business Owner at Location),Public,Free,HIB Petrol Caglavice,Prishtina-Skopje Highway; Prishtinë,NaN,Municipality of Gračanica / Graçanica,NaN,Kosovo,42.603811,21.132543,50.0,2,"CCS (Type 2), CHAdeMO, Type 2 (Tethered Connec...",Operational,2020
257584,147834,E6E62B27-597C-4F8A-BB59-4D59FA71BD03,1,(Business Owner at Location),Public,Free,Shell Kosovo Prizren,Autobahn Ibrahim Rugova Exit R107,Prizren,NaN,2000,Kosovo,42.251699,20.709738,50.0,2,"CCS (Type 2), CHAdeMO, Type 2 (Tethered Connec...",Operational,2020

In [ ]:
# checking missing values
numerical_cols = dff.select_dtypes(include=['number']).columns.tolist()
print("Numerical columns:", numerical_cols)
dff[numerical_cols].isna().sum()

categorical_cols = dff.select_dtypes(include=['object']).columns.tolist()
print("Categorical columns:", categorical_cols)
dff[categorical_cols].isna().sum()

Numerical columns: ['StationID', 'DataProviderID', 'Latitude', 'Longitude', 'MaxPowerKW', 'FastChargeCount', 'YearCreated']
Categorical columns: ['UUID', 'Operator', 'UsageType', 'UsageCost', 'AddressTitle', 'AddressLine1', 'Town', 'StateOrProvince', 'Postcode', 'Country', 'ConnectionTypes', 'StatusType']

UUID                    0
Operator            39225
UsageType           35116
UsageCost          195766
AddressTitle            5
AddressLine1         1817
Town                22756
StateOrProvince     74752
Postcode            27075
Country                 0
ConnectionTypes      4876
StatusType          36392
dtype: int64